version: '3.9'

services:
  hello-world:
    container_name: hello-foobar
    image: "hello-world:latest"

    networks:
      - foobar

# with name property
# Compose file version >= 3.5
# https://docs.docker.com/compose/compose-file/compose-versioning/#version-35
networks:
  foobar:
    driver: bridge
    name: foobar